### PR TITLE
Fix for #15.

### PR DESCRIPTION
**Pull request by Levoment**
Fix for #15. Problem in which the player can only place a max of 64 rope ladders.

### CODE REVIEW

**Comment by Levoment** [comment]
The diff pretty much says everything has been removed and then re-added which makes it hard to see my changes, but the only method I modified was **onPlaced**. The rest is the same.

**Review by NeusFear — CHANGES_REQUESTED** [review]
Sorry for the late response, this one went under my nose, please use tabs instead of spaces.

**Review by Levoment — COMMENTED** [review]
It's okay. I have changed the spaces to tabs in the second commit: https://github.com/TerraformersMC/Campanion/commit/7b8ab9fb5ae999829c3477be9378d04f758a33f6

What I don't know though is how to make the pull request take that last commit instead of the one submitted here. Don't know if I need to close this PR and submit the latest one which is 2 commits ahead.

Thanks.

**Comment by Levoment** [comment]
Yes, I just noticed that the changes can only be done on a new commit and it's not possible to modify this one unless amend is used. I will close this pull request and make a new pull request with the one that has the spaces changed to tabs.

**Pull request closed without merging**
