### PR TITLE
Fix compat with nourish

### PR DESCRIPTION
**Pull request by Cooliosity**
The mod in it's current state is incompatible with nourish due to the datapack files being placed in the wrong place, this PR fixes this issue.

### CODE REVIEW

**Comment by NeusFear** [comment]
This wasn't a mistake, I suppose that this may just be coincidental that both mods use the same datapack names. Our Json files here are used as tag categories for the MRE. Does this still work if nourish is not present?

**Comment by Cooliosity** [comment]
I don't understand what you are saying, english is not my native language.

**Comment by MrLoLf** [comment]
He asked if your fix works when nourish is not present as mod, so only Campanion is being used alone.

**Comment by Cooliosity** [comment]
I have absolutely no clue as this was two years ago

**Pull request closed without merging**
