### PR TITLE
Improved marshmallow, cracker and s'more textures

### PR DESCRIPTION
**Pull request by 20o**
Pretty much just the title also made some neat little preview images
image
image
image

### CODE REVIEW

**Comment by NeusFear** [comment]
Overall these look pretty nice, the crackers and the smores themselves look really great, however, I don't think that I like the melting look, marshmallows don't really do that when you cook them. The color of the blackened is too saturated I'd rather see it look more like a burnt marshmallow.

**Comment by Prospector** [comment]
I really like them too. Perhaps you could keep them a little melty but maybe make it droop down a little less? It sorta looks like it's made of slime or something, when really it sorta crispens on the outside (though a little bit of deformation could look nice and give it a unique shape from the "raw" one). I also agree that the blackened ones could maybe be a bit more grey/black. My only other concern would be the size of the marshmallows and whether or not it feels off in-game. Perhaps it's fine though, I'd have to see it in-game to tell.

Good work overall, though 👍

**Comment by 20o** [comment]
I made a few versions of the cooked/blackened ones, pretty sure the ones on the right look like teeth lol
also looking now the original blackened ones are pretty saturated

image
image

**Comment by Prospector** [comment]
I like those middle ones!

**Review by Prospector — APPROVED** [review]
LGTM!

**Comment by 20o** [comment]
Thanks!

**Comment by NeusFear** [comment]
Yeah these look great

**Review by ghost — APPROVED** [review]
👍🏻

**Review by NeusFear — APPROVED** [review]

**Pull request merged**
